### ISSUE TITLE
configurable search fields

### ISSUE THREAD

**Issue by timhemel** [benfowler/telescope-luasnip.nvim#11]
In my snippets, I would like to search for snippets that contain a certain text.

For this, the docstring would need to be added to the ordinal. I can imagine this can have a performance impact, therefore it would be nice to make this configurable via an option, or more generally, if I could provide a search callback function.

**Comment by timhemel** [comment]
The above PR lets you do this in the telescope config:
```
local lst = require('telescope').extensions.luasnip
local luasnip = require('luasnip')

require('telescope').setup {
    extensions = {
        ...
        luasnip = {
                search = function(entry)
                        return lst.filter_null(entry.context.trigger) .. " " ..
                                 lst.filter_null(entry.context.name) .. " " ..
                                 entry.ft .. " " ..
                                 lst.filter_description(entry.context.name, entry.context.description) ..
                                 lst.get_docstring(luasnip, entry.ft, entry.context)[1]
                end
        },
       ...
    }
}
```

**Comment by benfowler** [comment]
Thanks for your PR, @timhemel ! I've merged it, and I'll document the new search function hook now.
