### ISSUE TITLE
FR: Alternative Command to search *all snippets*, not just the ones active for the current filetype

### ISSUE THREAD

**Issue by chrisgrieser** [benfowler/telescope-luasnip.nvim#17]
right now, the plugin only shows me the snippets which are active in the current filetype. However, sometimes I wanna search *all* of my snippets, e.g. when doing `fn.system()` in nvim-lua, I wanna look up a shell snippet. Right now, this is not possible.

**Comment by benfowler** [comment]
The way I've done this, is that I've put globally-visible snippets and filetype-specific snippets separately in Luasnip. This plugin relies on what Luasnip itself is reporting as usable. This plugin is "downstream" of Luasnip, so there's probably not a whole lot we can do ourselves.

Feel free to weigh in with any more ideas though!
