### ISSUE TITLE
'snippets' is a nil value when calling get_docstring

### ISSUE THREAD

**Issue by zeitchef** [benfowler/telescope-luasnip.nvim#3]
I'm getting the following error when running `:Telescope luasnip`. I've got LuaSnip installed and configured properly.

<img width="1298" alt="Screen Shot 2022-04-01 at 15 34 58" src="https://user-images.githubusercontent.com/6670659/161275353-9ee16726-8408-4d1b-8284-34dd13163312.png">

**Comment by benfowler** [comment]
Hi @zeitchef ! Thanks for the heads-up -- and yes -- this just bit me too.

I'll roll a fix, and then figure out how to implement a regression test.. LuaSnip keeps breaking things.

**Comment by benfowler** [comment]
This came up in LuaSnip's "Breaking Changes" tracking issue. 

https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1068545111

I saw this, but didn't have the presence of mind to re-test at the moment it happened. I'll know better for next time. Lesson learned!

**Comment by benfowler** [comment]
@zeitchef I've made the fix and ~~opened benfowler/telescope-luasnip.nvim#4 if you'd like to confirm it works for you too~~merged it. Let me know if it's still broken for you. I'll have a think about getting in some test coverage in the meantime.

**Comment by zeitchef** [comment]
@benfowler Thanks for the quick response. Works as expected!

**Comment by danielo515** [comment]
seems that the new API is `luasnip.available()` ? Dam, the amount of breaking changes of this project is frustrating

**Comment by benfowler** [comment]
It's not great. I also see issues with nvim-cmp, where stuff just breaks
with virtually zero notice. The latest one was where they decided to just
remove all the default keybindings with no notice, and then broke
tab-completion in command mode. I don't want to look a gift-horse in the
mouth though, but it isn't fun when you've got a day job and deadlines to
hit.

It looks like some projects are coming up with some sensible general rules
on when to break backwards compatibility and how to advertise them; like
having a pinned 'Breaking Changes' issue on each project, and only
introducing major breaking changes on new versions of Neovim, as
`lsp-config` just did today with the release of 0.7. This is all open
source, so people will just do what they want at the end of the day...

I think the best I can do at least with this piece of code, is to try and
find some time to write a regression test. The idea I had was to borrow
what some other Telescope extensions do, and write a test case to start
their plugins in Neovim configured with a minimum reproduction, and then
test basic functionality. Then set up a GitHub Action to run this nightly.

**Comment by danielo515** [comment]
I think that for all os us that use packer we should start pinning commit hashes just like we do with package-lock in other languages and then only upgrade to the latest during weekends with enough time to chase bugs.

**Comment by benfowler** [comment]
I just checked Packer's readme, and it makes a mention of snapshot functionality, which if I'm not mistaken, can be made to fit the bill. I'm going to see what prior art is already out there, and then give this a go -- good suggestion, @danielo515 👍
