### ISSUE TITLE
Problems loading extension into telescope.

### ISSUE THREAD

**Issue by 52617365** [benfowler/telescope-luasnip.nvim#8]
There is a problem when loading the extension into telescope. Problem appears when you follow the documentation provided on the repo page.

Luasnip is installed, telescope is installed and the extension is installed as the repo suggests.

Error only occurs once you call load_extension on it. Error does not appear once you comment the line out.

Full error message: https://pastebin.com/JPCLYKHH

Tell me if you need help, have a question.

**Comment by pjezusek** [comment]
Hi,
I just encountered the same error. My problem was that I had to call `PackerCompile` after adding the extensions to my `init.lua`. The command `PackerSync` was not enough. If you type `:checkhealth telescope` you should see something like this:

![image](https://user-images.githubusercontent.com/37087585/176870670-21e69412-0168-4e68-8d76-8fe3eb6fa738.png)

If you don't see this, try to use the command mentioned above.

PS.:

I'm loading the plugin without "lazy feature":
```
use {
  "benfowler/telescope-luasnip.nvim",
}
```

**Comment by benfowler** [comment]
Hi; I'll try and reproduce this.

**Comment by benfowler** [comment]
Is this still an issue? If so I'll follow up ASAP.

**Comment by benfowler** [comment]
I haven't seem any motion on this issue since, so I'll close it. 

Some fixes have recently been applied to fix module loading alongside certain other plugins. 

Shout if you see any regressions.
